server:
  port: 7777
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/easeblog?characterEncoding=utf-8&serverTimezones=Asia/Shanghai
    username: root
    password: 2020101642
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 0
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: wubfppxLHBwJD7zqNK4gvaTapKZCB2mSbTfdRgg5
  secretKey: gZ2qJgl5HMwjrZ7THzlL6SNwWinbwmwfhigSDgsB
  bucket: easeblog-oss
  # CDN测试域名
  domain: s03ckbt8r.hn-bkt.clouddn.com
